In [2]:
import os
import psycopg2
from sqlalchemy import create_engine
from dotenv import load_dotenv
import pandas as pd

In [3]:
# Parâmetros de conexão com o PostgreSQL
db_host = 'localhost'
db_port = os.getenv('DB_EXTERNAL_PORT')
db_database = os.getenv('DB_DATABASE')
db_user = os.getenv('DB_USER')
db_password = os.getenv('DB_PASSWORD')

In [8]:
try:
    # Testar conexão antes de prosseguir
    test_conn = psycopg2.connect(
        host=db_host,
        port=db_port,
        database=db_database,
        user=db_user,
        password=db_password
    )
    print("Conexão com o PostgreSQL estabelecida com sucesso!")
    test_conn.close()
except Exception as e:
    print(f"Erro ao estabelecer conexão com o PostgreSQL: {e}")

Conexão com o PostgreSQL estabelecida com sucesso!

In [5]:
engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_database}')

query = """-- Listar Tabelas
SELECT table_schema, table_name, 'table' AS type
FROM information_schema.tables
WHERE table_schema IN ('bronze', 'silver', 'gold')
  AND table_type = 'BASE TABLE'

UNION

-- Listar Views
SELECT table_schema, table_name, 'view' AS type
FROM information_schema.views
WHERE table_schema IN ('bronze', 'silver', 'gold')

UNION

-- Listar Views Materializadas
SELECT schemaname, matviewname AS table_name, 'materialized view' AS type
FROM pg_matviews
WHERE schemaname IN ('bronze', 'silver', 'gold')
ORDER BY table_schema, table_name;
"""
available_tables = pd.read_sql(query, con=engine)
available_tables

WARNING:  database "brt_db" has a collation version mismatch
DETAIL:  The database was created using collation version 2.36, but the operating system provides version 2.41.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE brt_db REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

  table_schema        table_name               type
0       bronze          brt_data              table
1         gold  vw_brt_last_info  materialized view

In [7]:
pd.read_sql("SELECT * FROM gold.vw_brt_last_info ORDER BY data DESC, hora DESC", con=engine)

           codigo        data      hora   latitude  longitude  velocidade
0          903022  2025-08-08  15:29:51 -22.837856 -43.290996         0.0
1          902319  2025-08-08  15:29:51 -22.885298 -43.235077        58.9
2          902344  2025-08-08  15:29:51 -22.965650 -43.396161        23.5
3          902382  2025-08-08  15:29:51 -22.850465 -43.398175         0.0
4          901005  2025-08-08  15:29:51 -22.965241 -43.391212         3.4
..            ...         ...       ...        ...        ...         ...
715        903019  2025-07-24  23:14:23 -22.774938 -43.284832         0.0
716        902257  2025-07-18  01:37:39 -22.919535 -43.646134         0.0
717    00140007D7  2025-07-17  16:55:03 -22.906183 -43.177643         0.0
718        903009  2025-07-15  13:36:38 -22.876579 -43.329644         0.0
719  RJG7D28 MOTO  2025-07-11  14:09:34 -23.000825 -43.364887         0.0

[720 rows x 6 columns]